### PR TITLE
Add documentation on pipeline deletion

### PR DESCRIPTION
**Pull request by pshelton-skype**
Add a warning about possible collisions when deleting pipelines.

### CODE REVIEW

**Comment by pshelton-skype** [comment]
Until https://github.com/gocd/gocd/issues/879 is resolved, we should document possible dangers with pipeline deletion.

**Comment by ketan** [comment]
Could you elaborate or provide a concrete example of what you mean by "may cause conflicts"

**Comment by pshelton-skype** [comment]
My team just hit the SQLException detailed at https://groups.google.com/forum/#!searchin/go-cd/sqlexception/go-cd/ftCO3UMrbrE/fulTbKqb7mQJ, which links to a related Google Groups discussion at https://groups.google.com/forum/#!topic/go-cd/LVnapi82dmg/discussion. It's a known issue that pipelines can't be re-created with the same name, but poorly communicated.

**Comment by pshelton-skype** [comment]
Just realized this was still open. Do we need more changes here or should this be merged?

**Pull request merged**
