### PR TITLE
remove trust.jks for multiple agents setup

### PR DESCRIPTION
**Pull request by abhishekkr**
Setting up multiple agents of Windows starts but raises SSL exception. Need to remove previous trust.jks to get it right; it get regenerated.

### CODE REVIEW

**Comment by zabil** [comment]
Hi, @abhishekkr  - would you mind signing the CLA it's a one time requirement.
Thanks for helping out!

**Comment by abhishekkr** [comment]
it's alright, I don't care whose commit updates it... can anyone who already has it signed (and agrees with this change) update it

**Comment by zabil** [comment]
Sorry, did not provide you a link. 
http://www.go.cd/contribute/cla.html 

If you don't want to sign that's ok we'll modify it ourselves. However we love contributions.

**Comment by abhishekkr** [comment]
I love contributing, just don't like SLA driven OSS. Thus stayed away from Canonical as well.
To each their own.

**Pull request closed without merging**
