### PR TITLE
Use XML Github-Flavored Markdown for plugins.xml example

### PR DESCRIPTION
**Pull request by sghill**
Also clean up indentation to allow for easy copying.

In the current documentation the xml tags are hidden:
screen shot 2015-10-12 at 11 11 52 pm

Changing the code fence to xml shows and syntax highlights the tags:

screen shot 2015-10-12 at 11 12 27 pm

### CODE REVIEW

**Comment by ketan** [comment]
@sghill - can you resolve the conflicts please?

**Comment by sghill** [comment]
@ketan Couldn't seem to squash the merge commit into the original commit -- are merge commits ok?

**Comment by ketan** [comment]
They're fine – I'm merging them in.

**Comment by sghill** [comment]
Thanks!

**Pull request merged**
