### PR TITLE
Fixed missing resources. Formatting and text

### PR DESCRIPTION
**Pull request by zabil**

### CODE REVIEW

**Comment by ketan** [comment]
@zabil - was there a reason to use triple backticks instead of single. Triple is usually used for code blocks, not inline.

Also, would you mind running the images through `optipng -o7` to reduce the sizes?

**Comment by ketan** [comment]
Scratch the optipng, I'll do that once after everything is in.

**Comment by zabil** [comment]
@ketan it was being used in the newer documentation.
https://github.com/gocd/documentation/blob/2d8ca027d1e1b8b2660d2667a2737a14a2f94099/user/installation/troubleshoot_installer.md

Made it consistent

**Comment by ketan** [comment]
> Made it consistent

:+1:

**Comment by arvindsv** [comment]
> ... it was being used in the newer documentation ...

Sorry. I start out making them not be inline and sometimes inline them. At least GFM handles it properly when it is inline and with three backticks. So, I just don't bother with the single backtick.

**Pull request merged**
