### PR TITLE
Update stages_api.md

### PR DESCRIPTION
**Pull request by reidca**
Added information on the scheduled_date field including links to how to convert it.

### CODE REVIEW

**Comment by arvindsv** [comment]
@reidca: Looks good! Could you please signing the [CLA](http://www.go.cd/contribute/cla.html). It's a legal requirement. I thought you had already signed it. But, couldn't find an entry.

Thank you!

**Comment by reidca** [comment]
Ok done. Thanks.

On 7 Apr 2015 18:59, Aravind SV <notifications@github.com> wrote:
@reidca: Looks good! Could you please signing the [CLA](http://www.go.cd/contribute/cla.html). It's a legal requirement. I thought you had already signed it. But, couldn't find an entry.

Thank you!

---

**Comment by arvindsv** [comment]
Merged. Thank you!

**Comment by arvindsv** [comment]
It can be seen at: http://www.go.cd/documentation/user/15.1.0/api/stages_api.html

**Pull request merged**
